//
//  Common.h
//  EnhanceDiskUtility
//
//  Created by Nickolas Pylarinos on 04/08/2017.
//  Copyright © 2017 ulcheats. All rights reserved.
//

/*
 *  This header includes stuff that all subprojects use!
 */

#ifndef Common_h
#define Common_h

#import <Foundation/Foundation.h>

NSString * kSMJobBlessHelperIdentifier = @"";   // generated by Xcode
                                                // can be changed under project settings!

#endif /* Common_h */
