//
//  Common.h
//  EnhanceDiskUtility
//
//  Created by Nickolas Pylarinos on 04/08/2017.
//  Copyright © 2017 ulcheats. All rights reserved.
//

/*
 *  This header includes stuff that are used by multiple files
 *  Includes common DUEErrors, some identifiers etc.
 */

#ifndef Common_h
#define Common_h

#import <Foundation/Foundation.h>

NSString * kEnhanceDiskUtilityBundleIdentifier = @"ulcheats.EnhanceDiskUtility";
NSString * kSMJobBlessHelperIdentifier = @"";   // ** TODO ** Should be generated by Xcode
                                                // and can be changed under project settings!

#endif /* Common_h */
